### ISSUE TITLE
FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by PavelTorgashov** [codehoose/real-world-map-data#5]
Method BaseOsm.GetAttribute fires the exception if numeric delimiter in system is not dot.
Probably you need to pass invariant culture to the method ChangeType:

`return (T)Convert.ChangeType(strValue, typeof(T), CultureInfo.InvariantCulture);`

in line 43 of BaseOsm.cs

**Comment by SiarheiPilat** [comment]
@PavelTorgashov the author [posted a fix](https://gist.github.com/codehoose/3def83027c56f9b9977ec05773d670ec) for this on their gist, you just need to replace BaseOsm.cs with that code. @sloankelly you can close the issue, fix confirmed with 2022.3.10f1

**Comment by codehoose** [comment]
Fixed! Feel free to branch from `main` and write a pull request for bug fixes. Thanks again for pinging this for my attention!
